import fs from 'node:fs'
import path from 'node:path'

// Old URL (no extension) -> new URL. Add an entry whenever a page moves or is renamed.
export const redirects: Record<string, string> = {
  '/master/sales/orders/quotations': '/master/sales/quotations-orders/create-quotation',
  '/master/sales/orders/orders': '/master/sales/quotations-orders/manage-orders',
  '/master/sales/orders/customers': '/master/sales/quotations-orders/manage-customers',
  '/master/sales/toInvoice': '/master/sales/invoicing/order-to-invoice',
  '/master/sales/products': '/master/sales/products-prices/manage-products',
  '/master/sales/settings': '/master/sales/configuration/settings',
  '/master/sales/configurations': '/master/sales/configuration/',
  '/master/project/projects': '/master/services/project/projects',
  '/master/project/tasks': '/master/services/project/tasks',
  '/master/project/configurations': '/master/services/project/configurations',
  '/master/project/settings': '/master/services/project/settings',
  '/master/advanced/chatter/actions/activity': '/master/getting-started/chatter/actions/activity',
  '/master/advanced/chatter/actions/file': '/master/getting-started/chatter/actions/file',
  '/master/advanced/chatter/actions/follower': '/master/getting-started/chatter/actions/follower',
  '/master/advanced/chatter/actions/log-note': '/master/getting-started/chatter/actions/log-note',
  '/master/advanced/chatter/actions/message': '/master/getting-started/chatter/actions/message',
  '/master/advanced/chatter/introduction': '/master/getting-started/chatter/introduction',
  '/master/contact/configurations': '/master/getting-started/contacts/configurations',
  '/master/contact/contacts': '/master/getting-started/contacts/contacts',
  '/master/employees/configurations': '/master/human-resources/employees/configurations',
  '/master/employees/departments': '/master/human-resources/employees/departments',
  '/master/employees/employees': '/master/human-resources/employees/employees',
  '/master/inventories/configurations/delivery': '/master/supply-chain/inventories/configurations/delivery',
  '/master/inventories/configurations/products': '/master/supply-chain/inventories/configurations/products',
  '/master/inventories/configurations/warehouse-management': '/master/supply-chain/inventories/configurations/warehouse-management',
  '/master/inventories/operations/adjustments': '/master/supply-chain/inventories/operations/adjustments',
  '/master/inventories/operations/transfers': '/master/supply-chain/inventories/operations/transfers',
  '/master/inventories/products/lots-serial-number': '/master/supply-chain/inventories/products/lots-serial-number',
  '/master/inventories/products/packages': '/master/supply-chain/inventories/products/packages',
  '/master/inventories/products/products': '/master/supply-chain/inventories/products/products',
  '/master/inventories/settings': '/master/supply-chain/inventories/settings',
  '/master/invoice/configuration/bank-accounts': '/master/finance/invoices/configuration/bank-accounts',
  '/master/invoice/configuration/incoterms': '/master/finance/invoices/configuration/incoterms',
  '/master/invoice/configuration/index': '/master/finance/invoices/configuration/index',
  '/master/invoice/configuration/payment-terms': '/master/finance/invoices/configuration/payment-terms',
  '/master/invoice/configuration/product-attributes': '/master/finance/invoices/configuration/product-attributes',
  '/master/invoice/configuration/product-categories': '/master/finance/invoices/configuration/product-categories',
  '/master/invoice/configuration/settings': '/master/finance/invoices/configuration/settings',
  '/master/invoice/configuration/taxes': '/master/finance/invoices/configuration/taxes',
  '/master/invoice/configurations': '/master/finance/invoices/configuration/',
  '/master/invoice/customers/create-credit-note': '/master/finance/invoices/customers/create-credit-note',
  '/master/invoice/customers/create-invoice': '/master/finance/invoices/customers/create-invoice',
  '/master/invoice/customers/credit-notes': '/master/finance/invoices/customers/create-credit-note',
  '/master/invoice/customers/customers': '/master/finance/invoices/customers/manage-customers',
  '/master/invoice/customers/index': '/master/finance/invoices/customers/index',
  '/master/invoice/customers/invoices': '/master/finance/invoices/customers/create-invoice',
  '/master/invoice/customers/manage-customers': '/master/finance/invoices/customers/manage-customers',
  '/master/invoice/customers/payments': '/master/finance/invoices/customers/register-payment',
  '/master/invoice/customers/products': '/master/finance/invoices/products/manage-products',
  '/master/invoice/customers/register-payment': '/master/finance/invoices/customers/register-payment',
  '/master/invoice/index': '/master/finance/invoices/index',
  '/master/invoice/introduction': '/master/finance/invoices/',
  '/master/invoice/products/index': '/master/finance/invoices/products/index',
  '/master/invoice/products/manage-products': '/master/finance/invoices/products/manage-products',
  '/master/invoice/settings': '/master/finance/invoices/configuration/settings',
  '/master/invoice/vendors/bills': '/master/finance/invoices/vendors/create-bill',
  '/master/invoice/vendors/create-bill': '/master/finance/invoices/vendors/create-bill',
  '/master/invoice/vendors/create-refund': '/master/finance/invoices/vendors/create-refund',
  '/master/invoice/vendors/index': '/master/finance/invoices/vendors/index',
  '/master/invoice/vendors/manage-vendors': '/master/finance/invoices/vendors/manage-vendors',
  '/master/invoice/vendors/payments': '/master/finance/invoices/vendors/register-payment',
  '/master/invoice/vendors/products': '/master/finance/invoices/products/manage-products',
  '/master/invoice/vendors/refunds': '/master/finance/invoices/vendors/create-refund',
  '/master/invoice/vendors/register-payment': '/master/finance/invoices/vendors/register-payment',
  '/master/invoice/vendors/vendors': '/master/finance/invoices/vendors/manage-vendors',
  '/master/maintenance/configurations/categories': '/master/supply-chain/maintenance/configurations/categories',
  '/master/maintenance/configurations/stages': '/master/supply-chain/maintenance/configurations/stages',
  '/master/maintenance/configurations/teams': '/master/supply-chain/maintenance/configurations/teams',
  '/master/maintenance/equipments/equipments': '/master/supply-chain/maintenance/equipments/equipments',
  '/master/maintenance/operations/calendar': '/master/supply-chain/maintenance/operations/calendar',
  '/master/maintenance/operations/maintenance-requests': '/master/supply-chain/maintenance/operations/maintenance-requests',
  '/master/manufacturing/configurations/operations': '/master/supply-chain/manufacturing/configurations/operations',
  '/master/manufacturing/configurations/work-centers': '/master/supply-chain/manufacturing/configurations/work-centers',
  '/master/manufacturing/operations/manufacturing-orders': '/master/supply-chain/manufacturing/operations/manufacturing-orders',
  '/master/manufacturing/operations/work-orders': '/master/supply-chain/manufacturing/operations/work-orders',
  '/master/manufacturing/products/bills-of-material': '/master/supply-chain/manufacturing/products/bills-of-material',
  '/master/manufacturing/products/lots': '/master/supply-chain/manufacturing/products/lots',
  '/master/manufacturing/products/products': '/master/supply-chain/manufacturing/products/products',
  '/master/manufacturing/settings': '/master/supply-chain/manufacturing/settings',
  '/master/purchase/configurations': '/master/supply-chain/purchase/configurations',
  '/master/purchase/orders/purchase-agreements': '/master/supply-chain/purchase/orders/purchase-agreements',
  '/master/purchase/orders/purchase-orders': '/master/supply-chain/purchase/orders/purchase-orders',
  '/master/purchase/orders/quotations': '/master/supply-chain/purchase/orders/quotations',
  '/master/purchase/orders/vendors': '/master/supply-chain/purchase/orders/vendors',
  '/master/purchase/products': '/master/supply-chain/purchase/products',
  '/master/purchase/settings': '/master/supply-chain/purchase/settings',
  '/master/recruitment/applications': '/master/human-resources/recruitment/applications',
  '/master/recruitment/configuration': '/master/human-resources/recruitment/configuration',
  '/master/timeOff/configuration': '/master/human-resources/time-off/configuration',
  '/master/timeOff/management': '/master/human-resources/time-off/management',
  '/master/timeOff/my-time': '/master/human-resources/time-off/my-time',
  '/master/timeOff/overview': '/master/human-resources/time-off/overview',
  '/master/timeOff/reporting': '/master/human-resources/time-off/reporting'
}

// Writes a small HTML page at every old URL that forwards to the new one.
export function writeRedirects(outDir: string) {
  for (const [from, to] of Object.entries(redirects)) {
    const file = path.join(outDir, from.replace(/^\//, '') + '.html')
    fs.mkdirSync(path.dirname(file), { recursive: true })
    fs.writeFileSync(
      file,
      `<!doctype html><html><head><meta charset="utf-8"><title>Redirecting</title><link rel="canonical" href="${to}"><meta http-equiv="refresh" content="0; url=${to}"><script>location.replace(${JSON.stringify(to)})</script></head><body><a href="${to}">Page moved</a></body></html>`
    )
  }
}
